name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile CSS from SCSS files
      uses: gha-utilities/sass-build@v0.2.6
      with:
        source: src/styles/*.scss
        destination: assets/css
    - name: Add and Commit changes to pr-pages branch
      run: |
        git config --local user.email 'action@github.com'
        git config --local user.name 'GitHub Action'
        git add assets/css/*
        git commit -m 'Updates compiled CSS files'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
